name: Test compiler

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Create build directory
        run: mkdir -p build

      - name: Configure CMake
        run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}

      - name: Create artifacts directory
        run: mkdir -p ${{ github.workspace }}/artifacts

      - name: Prepare build artifacts
        run: mv ${{ github.workspace }}/build ${{ github.workspace }}/artifacts/build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v6
        with:
          name: build
          path: ${{ github.workspace }}/artifacts

  test-x86:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get build artifacts
        uses: actions/download-artifact@v8
        with:
          name: build

      - name: Make compiler executable
        run: chmod +x ${{ github.workspace }}/build/dumb

      - name: Install test dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip graphviz nasm
          pip3 install -r ${{ github.workspace }}/requirements.txt

      - name: Run tests
        working-directory: ${{ github.workspace }}/build
        run: ctest -V --timeout 1000 -C ${{ env.BUILD_TYPE }} --output-on-failure -R tests_x86

  test-ast:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get build artifacts
        uses: actions/download-artifact@v8
        with:
          name: build

      - name: Make interpreter executable
        run: chmod +x ${{ github.workspace }}/build/dumb_ast_interpreter

      - name: Install test dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip graphviz
          pip3 install -r ${{ github.workspace }}/requirements.txt

      - name: Run tests
        working-directory: ${{ github.workspace }}/build
        run: ctest -V --timeout 1000 -C ${{ env.BUILD_TYPE }} --output-on-failure -R tests_ast

  test-ir:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get build artifacts
        uses: actions/download-artifact@v8
        with:
          name: build

      - name: Make interpreter executable
        run: chmod +x ${{ github.workspace }}/build/dumb_ir_interpreter

      - name: Install test dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip graphviz
          pip3 install -r ${{ github.workspace }}/requirements.txt

      - name: Run tests
        working-directory: ${{ github.workspace }}/build
        run: ctest -V --timeout 1000 -C ${{ env.BUILD_TYPE }} --output-on-failure -R tests_ir

  time-benchmark:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Get build artifacts
        uses: actions/download-artifact@v8
        with:
          name: build

      - name: Make compiler executable
        run: chmod +x ${{ github.workspace }}/build/dumb

      - name: Install test dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip graphviz nasm hyperfine
          pip3 install -r ${{ github.workspace }}/requirements.txt

      - name: Run Python script and save JSON
        id: run_script
        run: |
          python test/benchmark.py ${{ github.workspace }}/build/dumb ${{ github.workspace }} > result.json

      - name: Parse JSON and output Markdown table
        run: |
          echo "### 📊 Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

            "name":                       test,
            "No optimizations":           result_false_false,
            "--enable-sccp":              result_true_false,
            "--enable-sccp --enable-dce": result_true_true

          jq -r '["|Name|", "No optimizations|", "--enable-sccp|", "--enable-sccp --enable-dce"], ["|:----|", "----:|", "----:|", "----:|"], (.[] | ["|" + .name + "|", .no_opt + "|", .sccp + "|", .sccp_dce + "|"]) | @tsv' result.json >> $GITHUB_STEP_SUMMARY
